amcl:
  ros__parameters:

    # 1. 좌표계
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"

    # 2. 센서
    scan_topic: "scan"

    # 3. 로봇 운동 모델
    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    # 4. Particle
    min_particles: 500
    max_particles: 2000

    # 5. 갱신 조건
    update_min_d: 0.25
    update_min_a: 0.2

    # 6. Laser 모델
    laser_model_type: "likelihood_field"
    max_beams: 60

    # 7. TF
    tf_broadcast: true